#version 450

// Constant PI
const float PI = 3.1415926;

layout(local_size_x=8, local_size_y=8, local_size_z=1) in;

layout(set=0, binding=0, std140) uniform InFace 
{
	mat3x3 WORLD_FROM_IN_PX;
};
layout(set=0, binding=1, rgba32f ) uniform restrict readonly image2D inFace;

layout(set=1, binding=0, std140) uniform OutFace 
{
	mat3x3 WORLD_FROM_OUT_PX;
};
layout(set=1, binding=1, rgba32f ) uniform restrict image2D outFace;

layout(set=2, binding=0) uniform Roughness 
{
	float roughness;
};

float D_GGX(float NoH, float a)
{
	float a2 = a * a;
	float f = (NoH * a2 - NoH) * NoH + 1.0f;
	return a2 / (PI * f * f);
}

vec2 Hammersley(uint i, uint N)
{
	uint bits = (i << 16u) | (i >> 16u);
	bits = ((bits & 0x55555555u) << 1u) | ((bits & 0xAAAAAAAAu) >> 1u);
    bits = ((bits & 0x33333333u) << 2u) | ((bits & 0xCCCCCCCCu) >> 2u);
    bits = ((bits & 0x0F0F0F0Fu) << 4u) | ((bits & 0xF0F0F0F0u) >> 4u);
    bits = ((bits & 0x00FF00FFu) << 8u) | ((bits & 0xFF00FF00u) >> 8u);
    float rbit = float(bits) * 2.3283064365386963e-10;
    return vec2(float(i) / float(N), rbit);
}

vec3 ImportanceSampleGGX(vec2 Xi, float Roughness, vec3 N) 
{
    float a = Roughness * Roughness;
    float phi = 2.0 * PI * Xi.x;
    float cosTheta = sqrt((1.0 - Xi.y) / (1.0 + (a*a - 1.0) * Xi.y));
    float sinTheta = sqrt(1.0 - cosTheta * cosTheta);
    
    vec3 H = vec3(sinTheta * cos(phi), sinTheta * sin(phi), cosTheta);
    
    vec3 up = abs(N.z) < 0.999 ? vec3(0,0,1) : vec3(1,0,0);
    vec3 tangent = normalize(cross(up, N));
    vec3 bitangent = cross(N, tangent);
    
    return tangent * H.x + bitangent * H.y + N * H.z;
}

void main() 
{
	ivec2 outSize = imageSize(outFace);
	if(gl_GlobalInvocationID.x >= outSize.x || gl_GlobalInvocationID.y >= outSize.y)
	{
		return;
	}

	vec2 uv = (vec2(gl_GlobalInvocationID.xy) + 0.5) / vec2(outSize);
	vec3 localPos = vec3(uv * 2.0 - 1.0, 1.0);
	vec3 N = normalize(WORLD_FROM_OUT_PX * localPos);
	vec3 V = N;

	vec3 prefilteredColor = vec3(0.0);
	float totalWeight = 0.0;
	const uint numSamples = 1024u;

	float inputSize = float(imageSize(inFace).x);

	for(uint i = 0u; i < numSamples; ++i)
	{
		vec2 Xi = Hammersley(i, numSamples);
		vec3 H = ImportanceSampleGGX(Xi, roughness, N);
		vec3 L = normalize(2.0 * dot(V, H) * H - V);

		float NDotL = clamp(dot(N, L), 0.0, 1.0);
		if(NDotL > 0.0)
		{
			float NDotH = clamp(dot(N, H), 0.0, 1.0);
			float VDotH = clamp(dot(V, H), 0.0, 1.0);
			float d = D_GGX(NDotH, roughness);
			float pdf = (d * NDotH) / (4.0 * VDotH + 0.0001);

			float saSample = 1.0 / (float(numSamples) * pdf + 0.0001);
			float saTexel = 4.0 * PI / (6.0 * inputSize * inputSize);
			float mipLevel = roughness == 0.0 ? 0.0 : 0.5 * log2(saSample / saTexel);
			prefilteredColor += imageLoad(inFace, ivec2(L.x, L.y)).rgb * NDotL;
			totalWeight += NDotL;
		}
	}

	vec3 result = prefilteredColor / (totalWeight + 0.0001);

	imageStore(outFace, ivec2(gl_GlobalInvocationID.xy), vec4(result, 0.0));
}

