#version 450

layout(local_size_x = 8, local_size_y = 8) in;

layout(rg16f, binding = 0) uniform image2D brdfLUT;

const uint SAMPLE_COUNT = 4096;

vec2 Hammersley(uint i, uint N)
{
	uint bits = (i << 16u) | (i >> 16u);
	bits = ((bits & 0x55555555u) << 1u) | ((bits & 0xAAAAAAAAu) >> 1u);
    bits = ((bits & 0x33333333u) << 2u) | ((bits & 0xCCCCCCCCu) >> 2u);
    bits = ((bits & 0x0F0F0F0Fu) << 4u) | ((bits & 0xF0F0F0F0u) >> 4u);
    bits = ((bits & 0x00FF00FFu) << 8u) | ((bits & 0xFF00FF00u) >> 8u);
    float rbit = float(bits) * 2.3283064365386963e-10;
    return vec2(float(i) / float(N), rbit);
}

// GGX importance sampling
vec3 ImportanceSampleGGX(vec2 Xi, float roughness) 
{
    float a = roughness * roughness;
    float phi = 2.0 * 3.14159265359 * Xi.x;
    float cosTheta = sqrt((1.0 - Xi.y) / (1.0 + (a*a - 1.0) * Xi.y));
    float sinTheta = sqrt(1.0 - cosTheta * cosTheta);

    return normalize(vec3(sinTheta * cos(phi), sinTheta * sin(phi), cosTheta));
}

// Smith geometry function
float GeometrySchlickGGX(float NdotV, float roughness) 
{
    float r = roughness + 1.0;
    float k = (r * r) / 8.0;
    return NdotV / (NdotV * (1.0 - k) + k);
}

float GeometrySmith(float NdotV, float NdotL, float roughness) 
{
    return GeometrySchlickGGX(NdotV, roughness) * GeometrySchlickGGX(NdotL, roughness);
}

void main() 
{
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(brdfLUT);
    if (pixel.x >= size.x || pixel.y >= size.y) return;

    float NdotV = (float(pixel.x) + 0.5) / float(size.x);
    float roughness = (float(pixel.y) + 0.5) / float(size.y);

    vec3 V = vec3(sqrt(1.0 - NdotV*NdotV), 0.0, NdotV);

    float A = 0.0;
    float B = 0.0;

    for (uint i = 0u; i < SAMPLE_COUNT; ++i) 
    {
        vec2 Xi = Hammersley(i, SAMPLE_COUNT);
        vec3 H = ImportanceSampleGGX(Xi, roughness);
        vec3 L = normalize(2.0 * dot(V,H) * H - V);

        float NdotL = max(L.z, 0.0);
        if (NdotL > 0.0) 
        {
            float NdotH = max(H.z, 0.0);
            float VdotH = max(dot(V,H), 0.0);

            float G = GeometrySmith(NdotV, NdotL, roughness);
            float G_Vis = (G * VdotH) / (NdotH * NdotV);

            float Fc = pow(1.0 - VdotH, 5.0);

            A += (1.0 - Fc) * G_Vis;
            B += Fc * G_Vis;
        }
    }

    A /= float(SAMPLE_COUNT);
    B /= float(SAMPLE_COUNT);

    imageStore(brdfLUT, pixel, vec4(A, B, 0.0, 1.0));
}